- name: Install Oranchelo icon theme
  pacaur:
    name: oranchelo-icon-theme
    state: present

- name: Setup wallpapers
  copy:
    src: "{{ item }}"
    dest: "{{home_directory}}/Pictures"
  with_fileglob:
    - roles/aesthetics/files/*
  become: False