- name: Check if ssh key exists
  stat:
    path: "{{ssh_directory}}/git"
  register: git_ssh_key_exists

- name: Generate ssh key for git
  shell: |
    ssh-keygen -t rsa -C "{{git_ssh_key_user}}" -f "{{ssh_directory}}/git" -N ''
  become: False
  when: git_ssh_key_exists.stat.exists == False

- name: Install npm
  pacman:
    name: npm
    state: present

- name: Install node manager
  npm:
    name: n
    global: yes
    state: present

- name: Install node.js 6
  shell: n 6.11.3

- name: Install coffee-script
  npm:
    name: coffee-script
    global: yes
    state: present

- name: Install webpack
  npm:
    name: webpack
    version: '2.2.0'
    global: yes
    state: present

- name: Install pip
  pacman:
    name: python-pip
    state: present

- name: Install httpie
  pip:
    name: httpie
    state: present

- name: Install pylint
  pip:
    name: pylint
    state: present

- name: Install virtualenv
  pip:
    name: virtualenv
    state: present

- name: Install Docker
  pacaur:
    name: docker
    state: present

- name: Install py-docker
  pip:
    name: docker
    version: 2.4.0
    state: present

- name: Install docker compose
  pip:
    name: docker-compose
    state: present

- name: Install AWS-Cli
  pip:
    name: awscli
    state: present

- name: Install Visual Studio Code
  pacaur:
    name: visual-studio-code
    state: present
  notify: Install vscode extensions

- name: Install Fiddler
  pacaur:
    name: fiddler
    state: present